spring.application.name=usuario
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.datasource.url=jdbc:oracle:thin:@fullstack1high
spring.datasource.username=GIMNASIOS
spring.datasource.password=Duoc$semestre03
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

oracle.net.tns_admin=C:/Users/mfran/Documents/GYM/wallet